server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://zhangsan:123456@localhost:3000/eureka/
      #defaultZone: http://localhost:3000/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
spring:
  application:
    name: demo