server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service_demo
          uri: lb://DEMO
          order: 0
          predicates:
            - Path=/demo/**
          filters:
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
  #设置访问eureka用户名密码
  security:
    user:
      name: zhangsan
      password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:3000/eureka/
      #defaultZone: http://localhost:3000/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

logging:
  level:
    org.springframework.cloud.gateway: debug
